nama = input("Nama Anda: ")
nim = input("NIM Anda: ")
alamat = input("Alamat Anda: ")
ttl = input("Tempat Tanggal Lahir: ")
hobby = input("Hobby: ")
print(nama)
print(nim)
print(alamat)
print(ttl)
print(hobby)
